{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injector-plugin",
    "version": "2.0.30",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "injector-plugin-2.0.30.jar",
          "url": "injector-plugin-2.0.30.jar",
          "size": 137557,
          "sha512": "7ec5fc82ff2a900094faa2357cdc154609036394219b9c2dffda0ebec07e384f77b6c7f26b8ea1db677c9e32b83ec6a04f87d9fb312bb033bd90ddb90d55fa28",
          "sha256": "eafb0cf8d9676a5b8fd296fbc62d6a3ba351e72cf044d91e722420ffc8ddc3e2",
          "sha1": "f3aa7dc5e0d1c18ac8b75f0f649712de98e83039",
          "md5": "642bc552c0956bb15bbe5300e371710a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          },
          "excludes": [
            {
              "group": "com.google.j2objc",
              "module": "j2objc-annotations"
            },
            {
              "group": "com.google.code.findbugs",
              "module": "jsr305"
            },
            {
              "group": "org.codehaus.mojo",
              "module": "animal-sniffer-annotations"
            },
            {
              "group": "com.google.errorprone",
              "module": "error_prone_annotations"
            }
          ]
        },
        {
          "group": "net.unethicalite",
          "module": "deobfuscator",
          "version": {
            "requires": "1.0.11-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "injector-plugin-2.0.30.jar",
          "url": "injector-plugin-2.0.30.jar",
          "size": 137557,
          "sha512": "7ec5fc82ff2a900094faa2357cdc154609036394219b9c2dffda0ebec07e384f77b6c7f26b8ea1db677c9e32b83ec6a04f87d9fb312bb033bd90ddb90d55fa28",
          "sha256": "eafb0cf8d9676a5b8fd296fbc62d6a3ba351e72cf044d91e722420ffc8ddc3e2",
          "sha1": "f3aa7dc5e0d1c18ac8b75f0f649712de98e83039",
          "md5": "642bc552c0956bb15bbe5300e371710a"
        }
      ]
    }
  ]
}
